<?php
include_once('checasesion.php');
include('php/conf/localeconf.php');
include('php/conf/menuconfig.php');
include('encabezado.php');
include('menusuperior.php');
include('menulateral.php');
include('principal.php');
include('pie.php');
?>
